DROP TABLE IF EXISTS parkingNodes;

CREATE TABLE parkingNodes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    content TEXT NOT NULL
);

CREATE TABLE parkingNodes (
    serialID INTEGER NOT NULL
    email TEXT NOT NULL
    nodeState TEXT NOT NULL
    
)